#!/bin/sh

LD_PRELOAD=/usr/local/lib/cegui-0.8.6/libCEGUIBase-0.so /usr/local/lib/cegui-0.8.6/libCEGUICommonDialogs-0.so /usr/local/lib/cegui-0.8.6/libCEGUICoreWindowRendererSet.so /usr/local/lib/cegui-0.8.6/libCEGUIExpatParser.so /usr/local/lib/cegui-0.8.6/libCEGUIIrrlichtRenderer-0.so /usr/local/lib/cegui-0.8.6/libCEGUIOpenGLRenderer-0.so /usr/local/lib/cegui-0.8.6/libCEGUISDL2ImageCodec.so /usr/local/lib/raknet/libRakNetDLL.so /usr/local/lib/irrKlang-1.5.0/libIrrKlang.so ./client_core
